In [1]:
import torch

In [14]:
x=torch.tensor(4.0,requires_grad=True)

In [15]:
y=x**2

In [16]:
z=torch.sin(y)

In [17]:
x

tensor(4., requires_grad=True)

In [18]:
y

tensor(16., grad_fn=<PowBackward0>)

In [19]:
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [20]:
z.backward()

In [21]:
x.grad

tensor(-7.6613)

In [22]:
###calculating for single pass

In [23]:
##manually

In [24]:
x1=torch.tensor(6.7)
y1=torch.tensor(0.0)


w=torch.tensor(1.0)
b=torch.tensor(0.0)

In [32]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [33]:
# Forward pass
z = w * x1 + b  # Weighted sum (linear part)
y_pred = torch.sigmoid(z)  # Predicted probability

# Compute binary cross-entropy loss
loss = binary_cross_entropy_loss(y_pred, y1)

In [34]:
loss

tensor(6.7012)

In [37]:
# Derivatives:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y1)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x1  # dz/dw = x
dz_db = 1  # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [38]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


In [30]:
####now will do using autograd

In [39]:
x2 = torch.tensor(6.7)
y2 = torch.tensor(0.0)
w1 = torch.tensor(1.0, requires_grad=True)
b1 = torch.tensor(0.0, requires_grad=True)

In [41]:
w1

tensor(1., requires_grad=True)

In [42]:
b1

tensor(0., requires_grad=True)

In [43]:
z=w1*x2+b1

In [44]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [45]:
y_pred=torch.sigmoid(z)

In [46]:
loss=binary_cross_entropy_loss(y_pred,y2)

In [47]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [48]:
loss.backward()

In [50]:
print(w1.grad)
print(b1.grad)

tensor(6.6918)
tensor(0.9988)


In [57]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [58]:
x

tensor([1., 2., 3.], requires_grad=True)

In [59]:
y=(x**2).mean()

In [60]:
y.backward()

In [61]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [56]:
x.grad.zero_()

tensor([0., 0., 0.])