In [12]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [13]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [14]:
tokenizer.fit_on_texts(docs)

In [15]:
len(tokenizer.word_index)

17

In [16]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [17]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Input

vocab_size = 18   # 0..17
seq_len = 5
embed_dim = 2

model = Sequential()
model.add(Input(shape=(seq_len,)))   # 👈 tells Keras the shape
model.add(Embedding(vocab_size, embed_dim))

model.summary()  # now shows (None, 5, 2) and params = 18*2 = 36


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 5, 2)           │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.compile('adam','accuracy')

In [26]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[[-0.00455133  0.0313843 ]
  [-0.04562059  0.01460664]
  [ 0.01005553  0.04110279]
  [ 0.01005553  0.04110279]
  [ 0.01005553  0.04110279]]

 [[-0.04562059  0.01460664]
  [-0.04562059  0.01460664]
  [ 0.01005553  0.04110279]
  [ 0.01005553  0.04110279]
  [ 0.01005553  0.04110279]]

 [[-0.01700699  0.00904821]
  [-0.01700699  0.00904821]
  [ 0.02240533 -0.0041911 ]
  [ 0.01005553  0.04110279]
  [ 0.01005553  0.04110279]]

 [[ 0.0215759  -0.04174573]
  [ 0.01320361 -0.0380343 ]
  [ 0.0215759  -0.04174573]
  [-0.04562059  0.01460664]
  [ 0.0215759  -0.04174573]]

 [[ 0.02268715  0.02349753]
  [-0.00933967 -0.04344163]
  [-0.02244645 -0.020595  ]
  [-0.00341503  0.02312617]
  [ 0.01005553  0.04110279]]

 [[ 0.02087778 -0.04098688]
  [ 0.02087778 -0.04098688]
  [ 0.01005553  0.04110279]
  [ 0.01005553  0.04110279]
  [ 0.01005553  0.04110279]]

 [[ 0.03716712  0.01453579]
  [ 0.03716712  0.01453579]
  [ 0.01005553  0.04110279]
  [ 0.01005553  0.04110279

In [28]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [29]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [30]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [31]:
X_train.shape

(25000, 50)

In [34]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

vocab_size = 10000
embed_dim = 2
max_len = 50   # sequence length after padding

model = Sequential([
    tf.keras.Input(shape=(max_len,)),         # 👈 define input shape here
    Embedding(vocab_size, embed_dim),         # no input_length needed
    SimpleRNN(32, return_sequences=False),
    Dense(1, activation='sigmoid')
])

model.summary()


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
import numpy as np

print(X_train.shape)
print("Max index in X_train:", np.max(X_train))
print("Max index in X_test :", np.max(X_test))


(25000, 50)
Max index in X_train: 88585
Max index in X_test : 88582


In [37]:
vocab_size = int(max(np.max(X_train), np.max(X_test)) + 1)
print("vocab_size =", vocab_size)


vocab_size = 88586


In [38]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
import tensorflow as tf

vocab_size = int(max(np.max(X_train), np.max(X_test)) + 1)
max_len = X_train.shape[1]   # sequence length (timesteps)

model = Sequential([
    tf.keras.Input(shape=(max_len,)),      # (batch_size, max_len)
    Embedding(vocab_size, 2),             # 👈 updated vocab_size
    SimpleRNN(32),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))


Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - acc: 0.5107 - loss: 0.6927 - val_acc: 0.5975 - val_loss: 0.6618
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - acc: 0.7070 - loss: 0.5628 - val_acc: 0.7984 - val_loss: 0.4458
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - acc: 0.8710 - loss: 0.3197 - val_acc: 0.7970 - val_loss: 0.4542
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - acc: 0.9255 - loss: 0.1991 - val_acc: 0.7935 - val_loss: 0.5505
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - acc: 0.9544 - loss: 0.1332 - val_acc: 0.7617 - val_loss: 0.5770
